# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 158764b8a288c0f0ee55506403e7b3eab6f165f4c50d445fb9ca9e87d86fdddb01ce9692a4a54053cf268e29eebabe6b8744b835038d19ae48a4aa3dfb71abfd

test:
  secret_key_base: c658e10ab63a394f907a74d6ee8da1dbef39364b8ce6123b1a739289f05aeeac4973bcc246040aaecb9cb6cce13f3ae8c0801763fbd6a88478a120ba226aac6f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
